steps:
  integrationArtifactUpdateConfiguration:
    cpiApiServiceKeyCredentialsId: roverpocServiceKeyCred
    integrationFlowId: httpdynamicUrls
    integrationFlowVersion: 2.1
    parameterKey: myheader
    parameterValue: test11
